//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: driverService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol DriverfindDriverCall: ClientCallUnary {}

fileprivate final class DriverfindDriverCallBase: ClientCallUnaryBase<DriverRequest, DriverResponse>, DriverfindDriverCall {
  override class var method: String { return "/Driver/findDriver" }
}


/// Instantiate DriverServiceClient, then call methods of this protocol to make API calls.
internal protocol DriverService: ServiceClient {
  /// Synchronous. Unary.
  func findDriver(_ request: DriverRequest, metadata customMetadata: Metadata) throws -> DriverResponse
  /// Asynchronous. Unary.
  @discardableResult
  func findDriver(_ request: DriverRequest, metadata customMetadata: Metadata, completion: @escaping (DriverResponse?, CallResult) -> Void) throws -> DriverfindDriverCall

}

internal extension DriverService {
  /// Synchronous. Unary.
  func findDriver(_ request: DriverRequest) throws -> DriverResponse {
    return try self.findDriver(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func findDriver(_ request: DriverRequest, completion: @escaping (DriverResponse?, CallResult) -> Void) throws -> DriverfindDriverCall {
    return try self.findDriver(request, metadata: self.metadata, completion: completion)
  }

}

internal final class DriverServiceClient: ServiceClientBase, DriverService {
  /// Synchronous. Unary.
  internal func findDriver(_ request: DriverRequest, metadata customMetadata: Metadata) throws -> DriverResponse {
    return try DriverfindDriverCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func findDriver(_ request: DriverRequest, metadata customMetadata: Metadata, completion: @escaping (DriverResponse?, CallResult) -> Void) throws -> DriverfindDriverCall {
    return try DriverfindDriverCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol DriverProvider: ServiceProvider {
  func findDriver(request: DriverRequest, session: DriverfindDriverSession) throws -> DriverResponse
}

extension DriverProvider {
  internal var serviceName: String { return "Driver" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/Driver/findDriver":
      return try DriverfindDriverSessionBase(
        handler: handler,
        providerBlock: { try self.findDriver(request: $0, session: $1 as! DriverfindDriverSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol DriverfindDriverSession: ServerSessionUnary {}

fileprivate final class DriverfindDriverSessionBase: ServerSessionUnaryBase<DriverRequest, DriverResponse>, DriverfindDriverSession {}

